# Generated by Django 4.2.3 on 2023-09-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='havedialog',
            name='last_message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
