# Generated by Django 4.2.3 on 2023-09-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_havedialog_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogs',
            name='was_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
