# Generated by Django 4.2.3 on 2023-09-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_dialogs_was_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='havedialog',
            name='status_message',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
