# Generated by Django 4.2.3 on 2023-09-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_havedialog_status_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='mysite/static/images/none_avatar.png', upload_to='mysite/static/images/', verbose_name='Аватарка'),
        ),
    ]
