# Generated by Django 4.2.3 on 2023-09-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogs',
            name='private_img',
            field=models.ImageField(blank=True, upload_to='mysite/static/images/'),
        ),
    ]
