# Generated by Django 4.2.3 on 2023-09-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_dialogs_private_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allchat',
            name='msg',
            field=models.TextField(blank=True, max_length=999999, null=True, verbose_name=''),
        ),
    ]
